### ISSUE TITLE
Update on Nigerian Phone numbers validation

### ISSUE THREAD

**Issue by Kolajosh** [shaolinmkz/nigeria-phone-number-validator#3]
Upon using this package I noticed that it doesn't work for the new format of Nigerian numbers: 091-xxx-xxx-xx.
But it works for other formats like 080-xxx-xxx-xx, 090-xxx-xxx-xx, etc.

Find the image link below.

![image](https://github.com/shaolinmkz/nigeria-phone-number-validator/assets/52327995/24ac1a09-fbb5-4cb6-a1ac-78ae9ecd22b5)

**Comment by shaolinmkz** [comment]
Issue has being addressed [here](https://github.com/shaolinmkz/nigeria-phone-number-validator/pull/4)
